name: king_search
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.10.9

dependencies:
  equatable: ^2.0.8
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  path: ^1.9.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  linux:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

msix_config:
  display_name: Kyng Search
  publisher_display_name: Reynegton Nunes
  identity_name: com.reynegton.kyngsearch
  msix_version: 0.1.0.2
  logo_path: assets/icon/app_icon.png
